// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dejcyzqcwsrdiqmckgis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlamN5enFjd3NyZGlxbWNrZ2lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjkxNDksImV4cCI6MjA1OTg0NTE0OX0.8Ysl6OAwPDJdITWEvLqSOLc0ZXSaeUV1gPq7j7VCVQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);